apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sec
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
    {{- range $k, $v := .Values.secret }}
    {{ $k }}: {{ $v | toString | b64enc }}
    {{- end }}