image:
  name: migration-repo-image
  tag: main

env:
  CLOUD_SQL_PORT: 5432

annotations_all:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
